events {
    worker_connections 100;
}

http {
    proxy_pass_header Set-Cookie;
    resolver 127.0.0.1 ipv6=off;
    server{
        listen 80;
        location / {
            proxy_pass http://app:8080;
        }
    }
}